name: Automated Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Bump version and generate changelog
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          npx standard-version
          git push --follow-tags origin main
